// Mock data for demonstration purposes
export const mockProducts = [
  {
    id: '1',
    name: 'Yoga Mat Non-Slip Exercise Mat',
    price: 850,
    reviews: 342,
    bsr: 1450,
    weight: 0.8,
    category: 'Sports & Fitness',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/yoga-mat-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  },
  {
    id: '2',
    name: 'Stainless Steel Water Bottle 750ml',
    price: 650,
    reviews: 287,
    bsr: 890,
    weight: 0.4,
    category: 'Home & Kitchen',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/water-bottle-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: true
  },
  {
    id: '3',
    name: 'Ceramic Coffee Mug Set',
    price: 1200,
    reviews: 156,
    bsr: 2100,
    weight: 1.2,
    category: 'Home & Kitchen',
    brandingPotential: 'Medium' as const,
    url: 'https://amazon.in/coffee-mug-example',
    isAmazonLaunched: false,
    isFragile: true,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  },
  {
    id: '4',
    name: 'Resistance Bands Set',
    price: 750,
    reviews: 423,
    bsr: 1850,
    weight: 0.6,
    category: 'Sports & Fitness',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/resistance-bands-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  },
  {
    id: '5',
    name: 'Bamboo Kitchen Utensil Set',
    price: 980,
    reviews: 203,
    bsr: 1650,
    weight: 0.7,
    category: 'Home & Kitchen',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/bamboo-utensils-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  },
  {
    id: '6',
    name: 'LED Desk Lamp',
    price: 1450,
    reviews: 678,
    bsr: 3200,
    weight: 1.1,
    category: 'Electronics',
    brandingPotential: 'Medium' as const,
    url: 'https://amazon.in/led-lamp-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: true,
    hasSizeVariations: false
  },
  {
    id: '7',
    name: 'Memory Foam Pillow',
    price: 1100,
    reviews: 89,
    bsr: 950,
    weight: 0.9,
    category: 'Home & Garden',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/memory-foam-pillow-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: true
  },
  {
    id: '8',
    name: 'Silicone Phone Case',
    price: 450,
    reviews: 234,
    bsr: 1200,
    weight: 0.1,
    category: 'Electronics Accessories',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/phone-case-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: true
  },
  {
    id: '9',
    name: 'Reusable Food Storage Containers',
    price: 890,
    reviews: 367,
    bsr: 1750,
    weight: 0.8,
    category: 'Home & Kitchen',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/food-containers-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  },
  {
    id: '10',
    name: 'Car Phone Mount',
    price: 650,
    reviews: 445,
    bsr: 1350,
    weight: 0.3,
    category: 'Automotive',
    brandingPotential: 'Low' as const,
    url: 'https://amazon.in/car-mount-example',
    isAmazonLaunched: false,
    isFragile: false,
    isFood: false,
    isElectronics: false,
    hasSizeVariations: false
  }
];